apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dispatcher-jira
  annotations:
    kubernetes.io/ingress.global-static-ip-name: lb-dispatcher-jira
    networking.gke.io/managed-certificates: dispatcher-jira
spec: 
  rules:
  - http: 
     paths: 
     - path: /healthy
       backend: 
        service: 
          name: dispatcher-jira
          port: 80